const guideFields = [
  {
    labelText: "Full Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Full name",
  },
  {
    labelText: "image",
    labelFor: "image",
    id: "image",
    name: "image",
    type: "text",
    autoComplete: "Image URL",
    isRequired: true,
    placeholder: "Profile picture",
  },
  {
    labelText: "languages",
    labelFor: "languages",
    id: "lang",
    name: "lang",
    type: "text",
    autoComplete: "x years",
    isRequired: true,
    placeholder: "Spoke Languages",
  },
  {
    labelText: "age",
    labelFor: "age",
    id: "age",
    name: "age",
    type: "text",
    autoComplete: "x years",
    isRequired: true,
    placeholder: "Age in years",
  },
  {
    labelText: "experience",
    labelFor: "experience",
    id: "exp",
    name: "exp",
    type: "text",
    autoComplete: "x years",
    isRequired: true,
    placeholder: "Working experience in years",
  },
  {
    labelText: "rate",
    labelFor: "rate",
    id: "rate",
    name: "rate",
    type: "number",
    autoComplete: "rate",
    isRequired: true,
    placeholder: "Rate per hour",
  },
  {
    labelText: "City",
    labelFor: "city",
    id: "city",
    name: "city",
    type: "text",
    autoComplete: "city",
    isRequired: true,
    placeholder: "City of service",
  },
];

export { guideFields };
